---
parser: babel-eslint
extends:
  - xo
  - prettier
env:
  es6: true
  node: true
  browser: true
plugins:
  - prettier
  - mocha
rules:
  max-nested-callbacks:
  - error
  - 20
globals:
  VERSION: true