version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - run: npm install
      - run: mkdir ./junit
      - run:
          command: npm test
          environment:
            JUNIT_REPORT_PATH: "./junit/"
            JUNIT_REPORT_NAME: "test-results.xml"
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
